import type { Metadata } from "next";
import { LegalLayout } from "@/src/components/legal/LegalLayout";
import "@/src/components/legal/legal.css";

export const metadata: Metadata = {
  title: "Privacy Policy | Delok",
  description:
    "Learn how Delok collects, uses, stores, and protects information when you use the Delok log monitoring platform.",
  alternates: { canonical: "https://delok.site/privacy" },
};

const TOC = [
  { id: "information-we-collect", label: "1. Information We Collect" },
  { id: "google-sign-in", label: "2. Google Sign-In" },
  { id: "how-we-use", label: "3. How We Use Information" },
  { id: "how-we-share", label: "4. How We Share Information" },
  { id: "data-storage", label: "5. Data Storage and Retention" },
  { id: "data-security", label: "6. Data Security" },
  { id: "cookies", label: "7. Cookies and Sessions" },
  { id: "choices", label: "8. Your Choices and Rights" },
  { id: "account-deletion", label: "9. Account Deletion" },
  { id: "third-party", label: "10. Third-Party Services" },
  { id: "international", label: "11. International Data Processing" },
  { id: "children", label: "12. Children's Privacy" },
  { id: "changes", label: "13. Changes to This Policy" },
  { id: "contact", label: "14. Contact" },
];

export default function PrivacyPage() {
  return (
    <LegalLayout
      title="Privacy Policy"
      lastUpdated="September 9, 2026"
      toc={TOC}
    >
      <p>
        Delok (&quot;Delok&quot;, &quot;we&quot;, &quot;us&quot;, or
        &quot;our&quot;) provides a log monitoring platform that allows
        developers and organizations to collect, store, and view application
        logs through the Delok service.
      </p>
      <p>
        This Privacy Policy explains what information we collect, how we use it,
        how we store and protect it, and the choices available to you when you
        use Delok.
      </p>
      <p>
        By using Delok, you acknowledge the practices described in this Privacy
        Policy.
      </p>

      <h2 id="information-we-collect">1. Information We Collect</h2>
      <p>
        We collect information that is necessary to provide and operate the
        Delok service.
      </p>

      <h3 id="account-information">1.1 Account Information</h3>
      <p>
        When you create or access a Delok account, we may collect information
        associated with your account, including:
      </p>
      <ul>
        <li>name;</li>
        <li>email address;</li>
        <li>profile picture, where provided;</li>
        <li>account identifiers; and</li>
        <li>authentication and session information.</li>
      </ul>
      <p>
        If you use Google Sign-In, some of this information may be provided to
        us by Google as part of the authentication process. Delok also supports
        GitHub as an additional sign-in option, which may provide similar basic
        profile information.
      </p>

      <h3 id="organization-project">
        1.2 Organization and Project Information
      </h3>
      <p>
        Delok may collect information that you provide when creating or managing
        organizations and projects, such as:
      </p>
      <ul>
        <li>organization names;</li>
        <li>project names;</li>
        <li>project identifiers; and</li>
        <li>configuration information associated with your projects.</li>
      </ul>
      <p>
        Delok supports organizations with roles (Owner and Member). Membership
        information (which users belong to which organizations and their role)
        is stored to enforce access control.
      </p>

      <h3 id="application-logs">1.3 Application Logs</h3>
      <p>
        Delok allows users to submit application logs through the Delok SDK or
        API using a project-scoped API key.
      </p>
      <p>
        Application logs may contain information generated by your application,
        including log messages, timestamps, severity levels (level),
        environment, event names, project identifiers, and other information
        included in the log event or optional payload submitted by you.
      </p>
      <p>
        The content of application logs is determined by you or by the
        application sending the logs to Delok.
      </p>
      <p>
        You are responsible for ensuring that you do not unnecessarily include
        passwords, API keys, authentication tokens, private keys, payment
        information, or other sensitive information in your application logs.
      </p>

      <h3 id="technical-info">1.4 Technical Information</h3>
      <p>
        When you use Delok, we may automatically receive limited technical
        information necessary to operate and secure the service, such as:
      </p>
      <ul>
        <li>IP address;</li>
        <li>browser or device information (user agent);</li>
        <li>request information;</li>
        <li>timestamps; and</li>
        <li>information relating to service errors or failures.</li>
      </ul>
      <p>
        We only collect technical information to the extent reasonably necessary
        for operating, maintaining, and securing Delok.
      </p>

      <h2 id="google-sign-in">2. Google Sign-In</h2>
      <p>
        Delok provides Google Sign-In as an authentication option (alongside
        GitHub Sign-In).
      </p>
      <p>
        When you sign in using Google, Delok may receive basic information
        associated with your Google account, such as your name, email address,
        profile picture, and a unique account identifier, depending on the
        permissions requested by Delok and the information provided by Google.
        Delok uses the default scopes provided by Better Auth for Google OAuth
        and does not request additional Google API scopes.
      </p>
      <p>We use information obtained through Google Sign-In to:</p>
      <ul>
        <li>authenticate your identity;</li>
        <li>create or access your Delok account;</li>
        <li>maintain your account;</li>
        <li>associate your Google identity with your Delok account; and</li>
        <li>provide access to the Delok service.</li>
      </ul>
      <p>
        Delok does not request access to your Google emails, Google Drive files,
        contacts, or other Google services unless explicitly stated and required
        by a future feature.
      </p>
      <p>We do not sell Google user data.</p>

      <h2 id="how-we-use">3. How We Use Information</h2>
      <p>
        We use the information we collect to provide and operate Delok. This may
        include using information to:
      </p>
      <ul>
        <li>create and maintain user accounts;</li>
        <li>authenticate users;</li>
        <li>manage organizations and projects;</li>
        <li>manage API keys for log ingestion;</li>
        <li>
          receive application logs submitted through the Delok SDK or API;
        </li>
        <li>process and store application logs;</li>
        <li>display application logs within the Delok dashboard;</li>
        <li>provide log viewing and search functionality;</li>
        <li>maintain the security and functionality of the service;</li>
        <li>troubleshoot service-related problems; and</li>
        <li>
          communicate with users about important matters relating to their
          account or the service.
        </li>
      </ul>

      <h2 id="how-we-share">4. How We Share Information</h2>
      <p>We do not sell your personal information.</p>
      <p>
        We may share or provide access to information to service providers that
        help us operate Delok, such as infrastructure, hosting, database,
        authentication, or other technical service providers.
      </p>
      <p>
        These providers may process information on our behalf and only to the
        extent necessary to provide their services.
      </p>
      <p>We may also disclose information if reasonably necessary to:</p>
      <ul>
        <li>comply with applicable law or legal process;</li>
        <li>respond to lawful requests from authorities;</li>
        <li>protect the security or integrity of Delok;</li>
        <li>prevent fraud, abuse, or unauthorized access; or</li>
        <li>
          protect the rights, property, or safety of Delok, our users, or
          others.
        </li>
      </ul>

      <h2 id="data-storage">5. Data Storage and Retention</h2>
      <p>
        We store account information and application data for as long as
        reasonably necessary to provide the Delok service and fulfill the
        purposes described in this Privacy Policy.
      </p>
      <p>
        The retention period for application logs may depend on service
        configuration and operational limitations. Delok does not currently
        advertise a specific guaranteed retention period or configurable
        retention settings.
      </p>
      <p>
        When information is no longer required, we may delete or anonymize it,
        subject to technical, legal, or operational requirements.
      </p>

      <h2 id="data-security">6. Data Security</h2>
      <p>
        We take reasonable technical and organizational measures designed to
        protect information against unauthorized access, alteration, disclosure,
        or destruction.
      </p>
      <p>However, no internet-based service can guarantee absolute security.</p>
      <p>
        You are also responsible for protecting your account credentials and for
        the information that you choose to submit to Delok.
      </p>

      <h2 id="cookies">7. Cookies and Sessions</h2>
      <p>
        Delok uses cookies and similar technologies that are necessary to
        authenticate users, maintain sessions, protect accounts, and provide
        essential functionality. Authentication is handled by Better Auth, which
        sets httpOnly, Secure, SameSite=None session cookies.
      </p>
      <p>These technologies may be necessary for Delok to function properly.</p>

      <h2 id="choices">8. Your Choices and Rights</h2>
      <p>
        Depending on applicable law, you may have rights regarding your personal
        information, including the right to:
      </p>
      <ul>
        <li>access information associated with your account;</li>
        <li>request correction of inaccurate information;</li>
        <li>request deletion of your account or personal information;</li>
        <li>withdraw consent where processing is based on consent; and</li>
        <li>
          request information about how your personal information is processed.
        </li>
      </ul>
      <p>
        You may also revoke Delok&apos;s access through your Google account
        settings if you have used Google Sign-In.
      </p>
      <p>
        Some information may need to be retained where required by law or where
        reasonably necessary for legitimate operational or security purposes.
      </p>

      <h2 id="account-deletion">9. Account Deletion</h2>
      <p>
        If you want to delete your Delok account, you may contact us using the
        contact information provided below.
      </p>
      <p>
        When an account is deleted, we will take reasonable steps to delete
        information associated with that account, subject to applicable legal,
        security, and operational requirements.
      </p>
      <p>
        Deletion of an account may also result in the deletion or loss of
        projects and application logs associated with that account.
      </p>

      <h2 id="third-party">10. Third-Party Services</h2>
      <p>
        Delok may rely on third-party services to operate parts of the platform,
        including hosting, database, authentication, infrastructure, and other
        technical services.
      </p>
      <p>
        Those services may process information on our behalf according to their
        own terms and privacy policies.
      </p>
      <p>
        Delok is not responsible for the privacy practices of third-party
        services that you access independently of Delok.
      </p>

      <h2 id="international">11. International Data Processing</h2>
      <p>
        Depending on the infrastructure and service providers used by Delok,
        your information may be processed or stored in countries other than the
        country in which you reside.
      </p>
      <p>
        Where required by applicable law, we will take appropriate measures for
        such transfers.
      </p>

      <h2 id="children">12. Children&apos;s Privacy</h2>
      <p>Delok is not intended for children under the age of 13.</p>
      <p>
        We do not knowingly collect personal information from children under 13.
      </p>
      <p>
        If you believe that a child has provided personal information to Delok,
        please contact us so that we can take appropriate action.
      </p>

      <h2 id="changes">13. Changes to This Privacy Policy</h2>
      <p>We may update this Privacy Policy from time to time.</p>
      <p>
        When we make changes, we will update the &quot;Last updated&quot; date
        at the beginning of this Privacy Policy.
      </p>
      <p>
        If we make significant changes, we may provide additional notice where
        required by applicable law.
      </p>

      <h2 id="contact">14. Contact</h2>
      <p>
        If you have questions, concerns, or requests regarding this Privacy
        Policy or your personal information, please contact us at:
      </p>
      <p>
        <strong>
          Email:{" "}
          <a href="mailto:yuandadhamap@gmail.com">yuandadhamap@gmail.com</a>
        </strong>
      </p>
    </LegalLayout>
  );
}
